version: '3'

services:
  db:
    image: 'postgres'
    volumes:
      - '.data/db:/var/lib/postgresql/data'
    restart: always
    environment:
      - POSTGRES_USER=fake
      - POSTGRES_PASSWORD=fakepassword

  api:
    depends_on:
      - 'db'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=build/libs/bank-0.0.1-SNAPSHOT.jar
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bank
      - DB_USERNAME=fake
      - DB_PASSWORD=fakepassword
